version: '3'
services:
    php-apache:
      build:
        context: ./php_client
      ports:
          - 80:80
      volumes:
          - ./php_client:/var/www/html
    db:
      build:
        context: ./MySQL
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: RestaurantDB
        MYSQL_USER: docker
        MYSQL_PASSWORD: docker
      container_name: golang_db
      ports:
        - "3306:3306"
      tty: true
    go:
      build:
        context: ./server
      volumes:
        - "./server:/go"
      container_name: golang_app
      ports:
        - "50051:50051"
      tty: true
      depends_on:
        - db
