<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: restaurant.proto

namespace Restaurant;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>restaurant.RestaurantId</code>
 */
class RestaurantId extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 rest_id = 1;</code>
     */
    private $rest_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $rest_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Restaurant::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 rest_id = 1;</code>
     * @return int
     */
    public function getRestId()
    {
        return $this->rest_id;
    }

    /**
     * Generated from protobuf field <code>int32 rest_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRestId($var)
    {
        GPBUtil::checkInt32($var);
        $this->rest_id = $var;

        return $this;
    }

}

