<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: restaurant.proto

namespace Restaurant;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>restaurant.Restaurant</code>
 */
class Restaurant extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 rest_id = 1;</code>
     */
    private $rest_id = 0;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>float rating = 3;</code>
     */
    private $rating = 0.0;
    /**
     * Generated from protobuf field <code>string cuisines = 4;</code>
     */
    private $cuisines = '';
    /**
     * Generated from protobuf field <code>string address = 5;</code>
     */
    private $address = '';
    /**
     * Generated from protobuf field <code>string timing = 6;</code>
     */
    private $timing = '';
    /**
     * Generated from protobuf field <code>int32 cft = 7;</code>
     */
    private $cft = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $rest_id
     *     @type string $name
     *     @type float $rating
     *     @type string $cuisines
     *     @type string $address
     *     @type string $timing
     *     @type int $cft
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Restaurant::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 rest_id = 1;</code>
     * @return int
     */
    public function getRestId()
    {
        return $this->rest_id;
    }

    /**
     * Generated from protobuf field <code>int32 rest_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRestId($var)
    {
        GPBUtil::checkInt32($var);
        $this->rest_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float rating = 3;</code>
     * @return float
     */
    public function getRating()
    {
        return $this->rating;
    }

    /**
     * Generated from protobuf field <code>float rating = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setRating($var)
    {
        GPBUtil::checkFloat($var);
        $this->rating = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cuisines = 4;</code>
     * @return string
     */
    public function getCuisines()
    {
        return $this->cuisines;
    }

    /**
     * Generated from protobuf field <code>string cuisines = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCuisines($var)
    {
        GPBUtil::checkString($var, True);
        $this->cuisines = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string address = 5;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>string address = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string timing = 6;</code>
     * @return string
     */
    public function getTiming()
    {
        return $this->timing;
    }

    /**
     * Generated from protobuf field <code>string timing = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setTiming($var)
    {
        GPBUtil::checkString($var, True);
        $this->timing = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 cft = 7;</code>
     * @return int
     */
    public function getCft()
    {
        return $this->cft;
    }

    /**
     * Generated from protobuf field <code>int32 cft = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setCft($var)
    {
        GPBUtil::checkInt32($var);
        $this->cft = $var;

        return $this;
    }

}

